# Generated by Django 4.1.6 on 2023-02-21 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('own_forms', '0001_models_changesss'),
    ]

    operations = [
        migrations.AddField(
            model_name='filledforms',
            name='xlsx_file',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='form',
            name='xlsx_file',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
