# Generated by Django 4.1.6 on 2023-02-13 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('own_forms', '0003_models_changes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='image',
            field=models.ImageField(null=True, upload_to='media/images/'),
        ),
    ]
